#!/usr/bin/env bash
#
# Common to server and worker installs.
#

set -e

echo "confirming needed files exist"

for f in rke2-images.linux-amd64.tar.zst rke2.linux-amd64.tar.gz sha256sum-amd64.txt install.sh; do
  if [[ ! -f /root/rke2-artifacts/$f ]]; then
    echo "missing required file: /root/rke2-artifacts/$f"
    exit 1
  fi
done

# per https://docs.rke2.io/known_issues/#networkmanager

if [[ ! -f /etc/NetworkManager/conf.d/rke2-canal.conf ]]; then
  echo "creating /etc/NetworkManager/conf.d/rke2-canal.conf"
  cat <<EOF > /etc/NetworkManager/conf.d/rke2-canal.conf
[keyfile]
unmanaged-devices=interface-name:cali*;interface-name:flannel*
EOF
fi

echo "restarting NetworkManager"

systemctl reload NetworkManager 

# TODO SET PROPER FIREWALL RULES FOR NOW JUST DISABLE FIREWALLD

echo "disabling firewalld"

systemctl stop firewalld && systemctl disable firewalld

# Configs mandated by Kubernetes docs

echo "configure socat"

yum -y install socat conntrack ipset

echo "disable swap"

[[ -z "$(swapon --show)" ]] || { swapoff -a; sed -i '/ swap /d' /etc/fstab; }
